# This is a basic workflow to help you get started with Actions

name: Deploy environment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy resources
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment sub create --location norwayeast \
            --parameters repositoryToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} \
            --template-file ./main.bicep
